name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt -- --check
  build:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y cmake libxcb-composite0-dev
      - name: Check
        run: cargo check
      - name: Clippy
        run: cargo clippy
      - name: cargo doc
        run: cargo doc --document-private-items --no-deps
  # If this fails, consider changing your text or adding something to .typos.toml
  # You can find typos here: https://crates.io/crates/typos'
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: check typos
        uses: crate-ci/typos@v1.23.2
